using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace GameState {

	public enum state {
		STANDBY, 
		ASKINGFORSTAGES, 
		ASKINGFORSINGLECARD, 
		ASKINGFORSPONSORS, 
		ASKINGFORPLAYERS, 
		ASKINGFORCARDSINQUEST,
		ASKINGFORSTAGEWEAPONS, 
		ASKINGFORCARDSINBID, 
		ASKINGFORCARDSTODISCARD,
		SHOWINGFOE,
		
		QUESTSTARTING,
		QUESTINPROGRESS,
		QUESTWRAPUP,
		DRAWINGSTORYCARD
		};

}
