using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace GameState {

	public enum state {
		STANDBY, 
		ASKINGFORSTAGES, 
		ASKINGFORSINGLECARD, 
		ASKINGFORSPONSORS, 
		ASKINGFORPLAYERS,
		ASKINGFORPLAYERSTOURNEY,
		ASKINGFORCARDSINQUEST,
		ASKINGFORCARDSINTOURNEY,
		ASKINGFORSTAGEWEAPONS, 
		ASKINGFORCARDSINBID, 
		ASKINGFORCARDSTODISCARD,
		ASKINGFORMORDREDTARGET,
		STARTINGTOURNEY,
		QUESTSTARTING,
		QUESTINPROGRESS,
		TOURNEYINPROGRESS,
		QUESTWRAPUP,
		TOURNEYWRAPUP,
		DRAWINGSTORYCARD,
		SHOWINGFOE,
		PROSPERITY,
		QUEENSFAVOR,
		KINGSCALL
		};
		

}
